[package]
name = "hello"
edition = "2024.beta"
license = "MIT"
authors = ["dogafincan"]

[dependencies]

[addresses]
hello = "0x159b80f0629ade2439d636749f99bafe5798741a6d5d64d03891a01dfe9c6aed"

[dev-dependencies]

[dev-addresses]
